name: hive_sembast_benchmark
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.27
  path: ^1.7.0
  cupertino_icons: ^0.1.2

  # Databases
  hive: ^1.4.4+1
  sembast: ^3.0.1  
  
dev_dependencies:
  build_runner: ^1.0.0
  hive_generator: ^0.8.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true